language: "zh"

pipeline:
- name: "tokenizer_jieba"
#- name: "ner_crf"
- name: "ner_bilstm_crf"
- name: "jieba_pseg_extractor"
  part_of_speech: ["nr"]


- name: "bert_vectors_featurizer"
  ip: 'localhost'
  port: 5555
  port_out: 5556
  show_server_config: True
  timeout: 10000
- name: "intent_classifier_tensorflow_embedding"

####################################################################

# language: "zh"

# pipeline:
# - name: "tokenizer_jieba"
# - name: "ner_crf"
# - name: "jieba_pseg_extractor"
#   part_of_speech: ["nr"]


# - name: "intent_featurizer_wordvector"
#   vector: "data/vectors.txt"

# - name: "intent_classifier_tensorflow_embedding"